script_arg <- grep('^--file=', commandArgs(FALSE), value = TRUE)
script_file <- normalizePath(sub('^--file=', '', script_arg[[1]]))
skill_root <- normalizePath(file.path(dirname(script_file), '..'))
source(file.path(skill_root, 'scripts', 'figure_style.R'))
library(ggplot2)
expect_error <- function(expr, pattern) {
  msg <- tryCatch({force(expr); ''}, error=function(e) conditionMessage(e))
  stopifnot(grepl(pattern, msg, fixed=TRUE))
}
font <- bf_font('Arial')
p <- ggplot(data.frame(x=1:3,y=2:4),aes(x,y))+geom_point()+bf_theme(font)+labs(x='Dose',y='Response')
expect_error(bf_prepare(p+labs(title='Publication-ready result'),font,c('Dose','Response','1','2','3','4')),'unrequested')
expect_error(bf_font('DefinitelyMissingFont'),'font')
expect_error(bf_prepare(p+annotate('text',x=2,y=3,label='Gene1',family='serif'),font,c('Dose','Response','Gene1','1','2','3','4')),'font')
expect_error(bf_prepare(p+annotate('text',x=2,y=3,label='AI insight',family='Arial'),font,c('Dose','Response','1','2','3','4')),'unapproved')
expect_error(bf_check_boxes(data.frame(id=c('data','legend'),x=c(0,8),y=c(0,0),w=c(10,4),h=c(10,4)),20,20),'overlap')
stopifnot(bf_check_boxes(data.frame(id=c('data','legend'),x=c(0,12),y=c(0,0),w=c(10,4),h=c(10,4)),20,20))
body <- bf_square_body(18,8,2,row_gaps_mm=c(1,1),column_gaps_mm=3)
stopifnot(body$width_mm==19,body$height_mm==38)
stopifnot(bf_label_angle(c('C1','R5'),font,7,2.5)==90)
stopifnot(bf_label_angle('C1',font,7,10)==0)
bf_complexheatmap_font(font)
stopifnot(grDevices::pdfFonts()[['Arial']]$family=='ArialMT')
# A long legend must not consume the data panel silently.
long_label<-paste(rep('Treatment',14),collapse=' ')
long_plot<-p+aes(colour=factor(x))+scale_colour_discrete(labels=rep(long_label,3))+scale_x_continuous(breaks=1:3)+scale_y_continuous(breaks=2:4)
long_prepared<-bf_prepare(long_plot,font,c('Dose','Response','1','2','3','4','factor(x)',long_label),width_mm=90,height_mm=75)
f<-tempfile(fileext='.png')
expect_error(bf_export_png(long_prepared,f,90,75),'insufficient panel')
stopifnot(!file.exists(f))

cat('STYLE_TESTS_OK\n')
