#!/usr/bin/env Rscript
suppressPackageStartupMessages({library(circlize); library(ComplexHeatmap); library(grid)})
set.seed(7801)
sizes <- c(40,40,40,90,15,80,50,5); lev <- c("M/T-II","T-II","T-IE M-II","ID","B-II","CD8-II","CD4-II","UC")
groups <- factor(rep(lev,sizes),levels=lev); n <- length(groups)
z <- matrix(rnorm(n*12,sd=.82),nrow=n,dimnames=list(paste0("gene",seq_len(n)),c("CD8.DEC","CD8.IFN","CD4.TCF","CD4.DEC","CD4.IFN","Treg","Mye.DEC","Mye.IFN","B.cell","Cancer","NK","Other")))
z[,1:3] <- z[,1:3]+(as.numeric(groups)-4)/4; score1 <- rep(0,n); score2 <- rep(0,n); score1[sample(n,50)]<-runif(50,-4,4); score2[sample(n,50)]<-runif(50,-2,2)
col_main=colorRamp2(c(-1,0,1),c("#1029E8","white","#F31B16")); col_s1=colorRamp2(c(-4,0,4),c("#A8D354","white","#F1814E")); col_s2=colorRamp2(c(-2,0,2),c("#71AED9","white","#ED5E55"))
ragg::agg_png("results/figures/issue078_circular_heatmap.png",width=2400,height=2400,res=300,background="white")
circos.clear(); circos.par(start.degree=90,gap.degree=c(rep(2,7),14),canvas.xlim=c(-1.01,1.11),canvas.ylim=c(-1.03,1.03))
circos.heatmap(z,split=groups,col=col_main,track.height=.35,dend.side="inside",dend.track.height=.20,rownames.side="outside",rownames.cex=.23)
circos.track(track.index=1,panel.fun=function(x,y) circos.text(CELL_META$xcenter,CELL_META$cell.ylim[2]+convert_y(5,"mm"),CELL_META$sector.index,facing="bending.inside",niceFacing=TRUE,cex=.95,font=2),bg.border=NA)
circos.heatmap(score1,col=col_s1,track.height=.04,bg.border="#333333",bg.lwd=.45); circos.heatmap(score2,col=col_s2,track.height=.04,bg.border="#333333",bg.lwd=.45)
draw(Legend(col_fun=col_s1,title="I.E. score",title_gp=gpar(fontsize=8,fontface=2),labels_gp=gpar(fontsize=7),grid_height=unit(3,"mm")),x=unit(.485,"npc"),y=unit(.50,"npc")); draw(Legend(col_fun=col_s2,title="ACT score",title_gp=gpar(fontsize=8,fontface=2),labels_gp=gpar(fontsize=7),grid_height=unit(3,"mm")),x=unit(.565,"npc"),y=unit(.50,"npc")); draw(Legend(col_fun=col_main,title="Expression",title_gp=gpar(fontsize=8,fontface=2),labels_gp=gpar(fontsize=7),grid_height=unit(3,"mm")),x=unit(.90,"npc"),y=unit(.14,"npc")); circos.clear(); dev.off()
write.csv(data.frame(gene=rownames(z),group=groups,z,IE=score1,ACT=score2,source="simulated",seed=7801),"results/plot_data/issue078_circular_heatmap.csv",row.names=FALSE)
