suppressPackageStartupMessages({library(ggplot2);library(dplyr);library(tidyr);library(patchwork);library(ggrepel)})
set.seed(20260913)
args<-commandArgs(trailingOnly=FALSE);script<-sub('--file=','',args[grep('--file=',args)]);root<-normalizePath(file.path(dirname(script),'..'))
figdir<-file.path(root,'results/figures');datdir<-file.path(root,'results/plot_data');dir.create(figdir,recursive=TRUE,showWarnings=FALSE);dir.create(datdir,recursive=TRUE,showWarnings=FALSE)
pal<-c('#4D3F72','#E9B949','#2A9D8F','#E76F51','#5B8FF9','#91CC75','#FAC858','#EE6666')
th<-theme_classic(base_family='Arial',base_size=9)+theme(axis.text=element_text(color='#222222'),plot.title=element_text(face='bold',hjust=.5,size=10),strip.background=element_blank(),legend.key=element_blank())
savep<-function(p,n,w=180,h=125)ggsave(file.path(figdir,n),p,width=w,height=h,units='mm',dpi=300,bg='white',device=ragg::agg_png)

# 41 three inset scatter panels.
mk41<-function(site){d<-tibble(x=rnorm(1500,0,.62),y=.63*x+rnorm(1500,0,.48),fc=pmax(-.3,pmin(.3,rnorm(1500,0,.16))));write.csv(d,file.path(datdir,paste0('batch41_',site,'.csv')),row.names=FALSE);base<-ggplot(d,aes(x,y))+ggrastr::geom_point_rast(aes(color=fc),size=.45,alpha=.55,dev='ragg')+scale_color_gradient2(low=pal[1],mid='grey92',high=pal[2],limits=c(-.3,.3),name='log2FC')+geom_hline(yintercept=0,color='grey80',linewidth=.2)+geom_vline(xintercept=0,color='grey80',linewidth=.2)+labs(x='SPF vs GF',y='FMT vs GF',title=site)+th
 up<-filter(d,x>1|y>1);lo<-filter(d,x< -1|y< -1);pup<-ggplot(up,aes(x,y,color=fc))+geom_point(size=.7)+scale_color_gradient2(low=pal[1],mid='grey92',high=pal[2],limits=c(-.3,.3),guide='none')+theme_classic(base_size=5)+theme(panel.border=element_rect(fill=NA,linewidth=.3));plo<-ggplot(lo,aes(x,y,color=fc))+geom_point(size=.7)+scale_color_gradient2(low=pal[1],mid='grey92',high=pal[2],limits=c(-.3,.3),guide='none')+theme_classic(base_size=5)+theme(panel.border=element_rect(fill=NA,linetype=2,linewidth=.3));base+inset_element(pup,.03,.70,.31,.98)+inset_element(plo,.69,.03,.97,.31)}
p41<-wrap_plots(lapply(c('Proximal colon','Middle colon','Distal colon'),mk41),nrow=1,guides='collect')&theme(legend.position='right');savep(p41,'revision_v1_41_inset_scatter.png',245,90)

# 42 faceted expression scatter with sparse labels.
d42<-expand_grid(interval=c('Duodenum','Jejunum','Ileum','Colon 1','Colon 2','Colon 3'),gene=paste0('Gene',1:650))|>mutate(spf=100*rbeta(n(),2,2),gf=pmax(0,pmin(100,spf+rnorm(n(),0,18))),fc=(spf-gf)/35,dir=case_when(fc > .5~'Up in SPF',fc < -.5~'Up in GF',TRUE~'NS'))|>group_by(interval)|>mutate(label=ifelse(rank(-abs(fc))<=4,gene,NA_character_))|>ungroup();write.csv(d42,file.path(datdir,'batch42_faceted_scatter.csv'),row.names=FALSE)
p42<-ggplot(d42,aes(spf,gf))+ggrastr::geom_point_rast(data=filter(d42,dir=='NS'),color='grey65',alpha=.25,size=.35,dev='ragg')+geom_point(data=filter(d42,dir!='NS'),aes(color=dir,size=abs(fc)),alpha=.85)+geom_abline(slope=1,color='grey75',linewidth=.25)+geom_hline(yintercept=50,linetype=2,linewidth=.25)+geom_vline(xintercept=50,linetype=2,linewidth=.25)+geom_text_repel(data=filter(d42,!is.na(label)),aes(label=label),size=2.2,max.overlaps=Inf,seed=20260913,box.padding=.2,min.segment.length=0)+facet_wrap(~interval,ncol=3)+scale_color_manual(values=c('Up in GF'=pal[1],'Up in SPF'=pal[2]))+scale_size(range=c(1,3))+labs(x='Percent expressed in SPF',y='Percent expressed in GF',color=NULL,size='Absolute average log2FC')+th+theme(legend.position='top');savep(p42,'revision_v1_42_faceted_gene_scatter.png',205,145)

# 43 subgroup forest using forestploter core.
suppressPackageStartupMessages({library(forestploter);library(grid)})
labs43<-c('Overall','Age','  <=70','  >70','ECOG status','  0–1','  2','Weight loss','  <=10 kg','  >10 kg','Performance','  <=80','  >80');est<-c(.78,NA,.72,.91,NA,.69,.97,NA,.75,.88,NA,.81,.76);lo<-est-runif(length(est),.12,.25);hi<-est+runif(length(est),.16,.31);n1<-sample(35:160,length(est),TRUE);n2<-sample(35:160,length(est),TRUE);df43<-data.frame(Subgroup=labs43,Dapagliflozin=ifelse(is.na(est),'',n1),Placebo=ifelse(is.na(est),'',n2),space='                    ',HR=ifelse(is.na(est),'',sprintf('%.2f (%.2f–%.2f)',est,lo,hi)),P=ifelse(is.na(est),'',sprintf('%.3f',runif(length(est),.002,.8))),check.names=FALSE);names(df43)[4]<-' ';write.csv(df43,file.path(datdir,'batch43_forest.csv'),row.names=FALSE)
tm<-forest_theme(base_size=9,ci_pch=15,ci_col='#222222',ci_fill='#222222',ci_lwd=1.2,refline_gp=gpar(lty=2,col='grey40'),core=list(padding=unit(c(2.2,2.2),'mm')));p43<-forest(df43,est=est,lower=lo,upper=hi,ci_column=4,ref_line=1,xlim=c(.35,1.45),ticks_at=c(.5,.75,1,1.25),arrow_lab=c('Treatment better','Control better'),theme=tm);ragg::agg_png(file.path(figdir,'revision_v1_43_subgroup_forest.png'),width=2300,height=2300,res=300,bg='white');plot(p43);dev.off()

# 44 waterfall with biomarker fills and TMB triangles.
n44<-48;d44<-tibble(id=factor(sprintf('P%02d',1:n44),levels=sprintf('P%02d',1:n44)),change=sort(runif(n44,-65,32),decreasing=TRUE),pdl1=sample(c('<10','≥10','Unknown'),n44,TRUE),tmb=sample(c(TRUE,FALSE),n44,TRUE,prob=c(.22,.78)));write.csv(d44,file.path(datdir,'batch44_waterfall.csv'),row.names=FALSE)
p44<-ggplot(d44,aes(id,change,fill=pdl1))+geom_col(width=.72,color='#222222',linewidth=.2)+geom_point(data=filter(d44,tmb),aes(y=change+ifelse(change>0,4,-4)),shape=24,size=2.5,fill='#1769AA',color='white',stroke=.25)+geom_hline(yintercept=c(-30,20),linetype=2,color='grey55',linewidth=.35)+scale_fill_manual(values=c('<10'='#9BD5E7','≥10'='#C8E0B4','Unknown'='#FAB79B'))+labs(x=NULL,y='Maximum change from baseline (%)',fill='PD-L1 CPS')+th+theme(axis.text.x=element_blank(),axis.ticks.x=element_blank(),legend.position='bottom');savep(p44,'revision_v1_44_waterfall.png',220,120)

# 45 swimmer with five milestone types.
n45<-34;d45<-tibble(id=factor(sprintf('%02d',1:n45),levels=sprintf('%02d',n45:1)),end=sort(runif(n45,5,31)),best=sample(c('CR','PR','SD','PD'),n45,TRUE))
events<-d45|>slice_sample(n=55,replace=TRUE)|>transmute(id,time=runif(n(),1,as.numeric(end)),event=sample(c('First response','First stable disease','Progressive disease'),n(),TRUE));write.csv(d45,file.path(datdir,'batch45_swimmer.csv'),row.names=FALSE)
p45<-ggplot(d45,aes(end,id,color=best))+geom_segment(aes(x=0,xend=end,yend=id),linewidth=.7)+geom_point(aes(shape=best),size=2)+geom_point(data=events,aes(time,id,shape=event),color='#333333',size=1.8,fill='white')+scale_color_manual(values=c(CR='#2A9D8F',PR='#5B8FF9',SD='#E9B949',PD='#E76F51'))+scale_shape_manual(values=c(CR=16,PR=17,SD=15,PD=4,'First response'=1,'First stable disease'=3,'Progressive disease'=8))+labs(x='Time since treatment initiation (months)',y=NULL,color='Best response',shape='Milestone')+th+theme(legend.position='right');savep(p45,'revision_v1_45_swimmer.png',215,165)

# 46 lollipop + GO enrichment bars.
terms<-c('neuron','oligodendrocyte','astrocyte','endothelial','mural cell','RBC','fibroblast','arachnoid barrier cell','ependymocyte','OPC','microglia','macrophage','T lymphocyte','B lymphocyte','unknown');d46<-tibble(cell=factor(terms,levels=rev(terms)),markers=sample(120:1700,length(terms)),p=10^runif(length(terms),-32,-3),go=c('synapse organization','glial cell differentiation','endothelial migration','regulation of muscle system','erythrocyte homeostasis','mesenchymal proliferation','extracellular structure organization','monocarboxylic acid transport','myeloid differentiation','axon ensheathment','immune activation','T cell activation','B cell activation','cell motility','localization'));write.csv(d46,file.path(datdir,'batch46_go.csv'),row.names=FALSE)
p46a<-ggplot(d46,aes(markers,cell,color=cell))+geom_segment(aes(x=0,xend=markers,yend=cell),color='grey82',linewidth=.4)+geom_point(size=2.8)+labs(x='Cell marker numbers',y=NULL)+th+theme(legend.position='none');p46b<-ggplot(d46,aes(-log10(p),cell,fill=cell))+geom_col(width=.62)+geom_text(aes(x=1,label=go),hjust=0,size=2.3,color='#222222')+labs(x='−log10(P value)',y=NULL)+th+theme(axis.text.y=element_blank(),axis.ticks.y=element_blank(),legend.position='none');savep(p46a+p46b+plot_layout(widths=c(1,1.35)),'revision_v1_46_lollipop_go.png',220,135)

# 47 Whittaker biome polygons from plotbiomes.
suppressPackageStartupMessages(library(plotbiomes));wb<-plotbiomes::Whittaker_biomes;pts<-tibble(temp=runif(24,7,28),prec=runif(24,25,260),z=runif(24,.05,.65));write.csv(pts,file.path(datdir,'batch47_biomes.csv'),row.names=FALSE)
p47<-ggplot()+geom_polygon(data=wb,aes(temp_c,precp_cm,group=biome,fill=biome),color='white',linewidth=.25,alpha=.86)+geom_point(data=pts,aes(temp,prec,size=z),shape=21,fill='#B45F77',color='white',stroke=.25,alpha=.82)+scale_fill_manual(values=plotbiomes::Ricklefs_colors)+scale_size(range=c(1.5,5),name=expression(Z[SAR]))+labs(x='Mean annual temperature (°C)',y='Mean annual precipitation (cm)',fill='Whittaker biomes')+th+theme(legend.position='right');savep(p47,'revision_v1_47_whittaker.png',180,135)

# 48 two ROC panels, pROC core.
suppressPackageStartupMessages(library(pROC));mkroc<-function(n,a,b){y<-rbinom(n,1,.45);s<-rnorm(n,a*y,b);roc(y,s,quiet=TRUE)};rocs1<-list(Train=mkroc(160,2.3,1),Test=mkroc(130,2,1),Validation=mkroc(120,1.8,1));rocs2<-list(Uganda=mkroc(130,2.1,1),Vietnam=mkroc(130,2.5,1),Philippines=mkroc(130,1.9,1));write.csv(data.frame(group=names(rocs1),auc=sapply(rocs1,auc)),file.path(datdir,'batch48_roc.csv'),row.names=FALSE)
rocplot<-function(rs,title){txt<-paste(sprintf('%s AUC = %.3f',names(rs),as.numeric(sapply(rs,auc))),collapse='\n');ggroc(rs,legacy.axes=TRUE,linewidth=.9)+geom_abline(slope=1,intercept=0,linetype=2,color='grey70')+annotate('text',x=.98,y=.05,label=txt,hjust=1,vjust=0,size=2.6,lineheight=.95)+scale_color_manual(values=pal[4:6])+coord_equal()+labs(x='1 − Specificity',y='Sensitivity',color=NULL,title=title)+th+theme(legend.position='bottom')};savep(rocplot(rocs1,'HIV negative only')+rocplot(rocs2,'ROC by country'),'revision_v1_48_dual_roc.png',190,95)

# 49 five Venn/Euler variants with their native packages.
suppressPackageStartupMessages({library(VennDiagram);library(eulerr);library(ggVennDiagram);library(ggvenn);library(cowplot)})
univ<-paste0('g',1:120);sets3<-list(A=sample(univ,55),B=sample(univ,68),C=sample(univ,72));sets4<-c(sets3,list(D=sample(univ,61)));sets5<-c(sets4,list(E=sample(univ,48)));write.csv(stack(sets5),file.path(datdir,'batch49_venn_sets.csv'),row.names=FALSE)
v1<-venn.diagram(sets3,filename=NULL,output=FALSE,disable.logging=TRUE,fill=c('#80C8CF','#FBB9C0','#FEF392'),alpha=.55,lty='blank',cat.cex=.7,cex=.7);p49a<-as_grob(v1);p49b<-as_grob(plot(euler(sets3),quantities=TRUE,fill=list(fill=c('#80C8CF','#FBB9C0','#FEF392'),alpha=.7),edges=list(col='grey35')));p49c<-ggVennDiagram(sets3,label_alpha=0,set_color='white')+scale_fill_gradient(low='#FFF5F0',high='#C92027')+theme_void();p49d<-ggvenn(sets4,fill_color=c('#8FC7A5','#FAA474','#9DAFD1','#E790C0'),fill_alpha=.45,stroke_linetype='dashed',show_percentage=FALSE);p49e<-as_grob(plot(euler(sets5),quantities=TRUE,fill=list(fill=RColorBrewer::brewer.pal(5,'Set2'),alpha=.35),edges=list(col=RColorBrewer::brewer.pal(5,'Set2'))));p49<-plot_grid(p49a,p49b,p49c,p49d,p49e,ncol=3,labels=c('Classic','Proportional','Count fill','Four sets','Five sets'),label_size=9);savep(p49,'revision_v1_49_venn_gallery.png',220,145)

# 50 faceted radar/spider using plotthis core.
suppressPackageStartupMessages(library(plotthis));d50raw<-expand_grid(x=LETTERS[1:10],Celltypes=c('Stalk-like','Tip-like'),Subtypes=c('SI','SII','SIII'),rep=1:8);d50raw$y<-runif(nrow(d50raw),.15,1);d50<-d50raw|>group_by(x,Celltypes,Subtypes)|>summarise(y=mean(y),.groups='drop');write.csv(d50,file.path(datdir,'batch50_radar.csv'),row.names=FALSE)
p50a<-RadarPlot(d50,x='x',y='y',group_by='Celltypes',scale_y='none',y_min=0,y_max=1,y_nbreaks=4,fill=TRUE,palcolor=c('#B66065','#9083AA'),facet_by='Subtypes',alpha=.35,combine=TRUE,legend.position='bottom');p50b<-SpiderPlot(filter(d50,Subtypes!='SIII'),x='x',y='y',group_by='Celltypes',scale_y='none',y_min=0,y_max=1,y_nbreaks=4,fill=TRUE,palcolor=c('#B66065','#9083AA'),facet_by='Subtypes',alpha=.28,combine=TRUE,legend.position='none');savep(p50a/p50b+plot_layout(heights=c(1.2,1)),'revision_v1_50_radar_spider.png',220,180)

writeLines(capture.output(sessionInfo()),file.path(root,'results/tables/sessionInfo.txt'))

# Remove device-only whitespace after every final render; add a stable white review margin.
for(fp in list.files(figdir,pattern='^revision_v1_.*\\.png$',full.names=TRUE)){
  im<-magick::image_read(fp)|>magick::image_trim()|>magick::image_border('white','24x24')
  magick::image_write(im,fp)
}
