suppressPackageStartupMessages({library(ggplot2);library(dplyr);library(tidyr);library(patchwork);library(ggrepel);library(ggtree)})
set.seed(20260913);args<-commandArgs(FALSE);script<-sub('--file=','',args[grep('--file=',args)]);root<-normalizePath(file.path(dirname(script),'..'));fd<-file.path(root,'results/figures');dd<-file.path(root,'results/plot_data');dir.create(fd,recursive=T,showWarnings=F);dir.create(dd,recursive=T,showWarnings=F)
pal<-c('#E76F51','#2A9D8F','#4C78A8','#F2C14E','#8F6BB3','#72B7B2','#D45087','#59656F');th<-theme_classic(base_family='Arial',base_size=9)+theme(axis.text=element_text(color='#222'),plot.title=element_text(face='bold',hjust=.5),strip.background=element_blank());sv<-function(p,n,w=180,h=125)ggsave(file.path(fd,sprintf('figure_%03d_%s.png',n,gsub(' ','_',tolower(nm)))) ,p,width=w,height=h,units='mm',dpi=300,bg='white',device=ragg::agg_png)
# 51 circular grouped heatmap
nm<-'circular_heatmap';m<-matrix(rnorm(18*28),18,dimnames=list(paste0('Gene',1:18),paste0('S',1:28)));write.csv(m,file.path(dd,'figure_051.csv'));ragg::agg_png(file.path(fd,'figure_051_circular_heatmap.png'),1800,1800,res=300,bg='white');circlize::circos.clear();circlize::circos.heatmap(m,col=circlize::colorRamp2(c(-2,0,2),c('#37659B','white','#D65F5F')),cluster=TRUE,dend.side='inside',rownames.side='outside',rownames.cex=.45);circlize::circos.clear();dev.off()
# common synthetic single-cell embedding
cells<-bind_rows(lapply(1:10,function(k)tibble(x=rnorm(220,cos(k)*2.6,.55),y=rnorm(220,sin(k)*2.2,.55),cluster=paste0('C',k),condition=sample(c('Ctrl','Treat'),220,T))));write.csv(cells,file.path(dd,'single_cell_embedding.csv'),row.names=F)
#52 UMAP + proportions
nm<-'umap_composition';p1<-ggplot(cells,aes(x,y,color=cluster))+geom_point(size=.35,alpha=.75)+scale_color_manual(values=rep(pal,length.out=10))+coord_equal()+theme_void()+theme(legend.position='right');pr<-count(cells,condition,cluster)|>group_by(condition)|>mutate(frac=n/sum(n));p2<-ggplot(pr,aes(condition,frac,fill=cluster))+geom_col()+scale_fill_manual(values=rep(pal,length.out=10))+labs(x=NULL,y='Cell fraction')+th+theme(legend.position='none');sv(p1+p2,52,210,105)
#53 marker heatmap
nm<-'marker_heatmap';mat<-matrix(rnorm(24*10),24,dimnames=list(paste0('Marker',1:24),paste0('C',1:10)));for(i in 1:10)mat[((i-1)*2+1):min(i*2+2,24),i]<-mat[((i-1)*2+1):min(i*2+2,24),i]+2;write.csv(mat,file.path(dd,'figure_053.csv'));ragg::agg_png(file.path(fd,'figure_053_marker_heatmap.png'),1900,1500,res=300,bg='white');ComplexHeatmap::draw(ComplexHeatmap::Heatmap(mat,name='Scaled expression',col=circlize::colorRamp2(c(-2,0,3),c('#2D5B8A','white','#E84A5F')),cluster_columns=FALSE,row_names_gp=grid::gpar(fontfamily='Arial',fontsize=7),column_names_gp=grid::gpar(fontfamily='Arial',fontsize=8),top_annotation=ComplexHeatmap::HeatmapAnnotation(cluster=colnames(mat),col=list(cluster=setNames(rep(pal,length.out=10),colnames(mat))))));dev.off()
#54 cell communication chord + alluvial
nm<-'cell_communication';edges<-expand_grid(source=paste0('C',1:7),target=paste0('C',1:7))|>filter(source!=target)|>mutate(weight=sample(1:25,n(),T));write.csv(edges,file.path(dd,'figure_054.csv'),row.names=F);ragg::agg_png(file.path(fd,'f54a.png'),1300,1300,res=300,bg='white');circlize::circos.clear();circlize::chordDiagram(edges,grid.col=setNames(pal[1:7],paste0('C',1:7)),transparency=.5,annotationTrack='grid');circlize::circos.clear();dev.off();flow<-expand_grid(axis=c('Sender','Pathway','Receiver'),id=1:180)|>mutate(stratum=case_when(axis=='Sender'~sample(paste0('C',1:5),n(),T),axis=='Pathway'~sample(paste0('P',1:6),n(),T),TRUE~sample(paste0('C',6:10),n(),T)));p54<-ggplot(flow,aes(axis,1,alluvium=id,stratum=stratum,fill=stratum))+ggalluvial::geom_alluvium(alpha=.35,width=.18)+ggalluvial::geom_stratum(width=.22,color='white')+theme_void()+theme(legend.position='none');sv(p54,54,105,105);magick::image_append(c(magick::image_read(file.path(fd,'f54a.png'))|>magick::image_trim(),magick::image_read(file.path(fd,'figure_054_cell_communication.png'))|>magick::image_trim()),stack=F)|>magick::image_write(file.path(fd,'figure_054_cell_communication.png'));unlink(file.path(fd,'f54a.png'))
#55 clustered network
nm<-'cluster_network';g<-igraph::sample_pa(180,2,directed=F);igraph::V(g)$group<-sample(letters[1:8],igraph::vcount(g),T);p<-ggraph::ggraph(g,layout='stress')+ggraph::geom_edge_link(color='grey75',alpha=.35,linewidth=.25)+ggraph::geom_node_point(aes(color=group),size=1.7)+scale_color_manual(values=pal)+theme_void()+theme(legend.position='right');sv(p,55,160,130)
#56 differentiation potential UMAP
nm<-'cytotrace';d56<-cells|>mutate(score=scales::rescale(x+y));write.csv(d56,file.path(dd,'figure_056.csv'),row.names=F);p<-ggplot(d56,aes(x,y,color=score))+geom_point(size=.45)+scale_color_viridis_c(option='plasma',direction=-1)+coord_equal()+theme_void()+labs(color='CytoTRACE score');sv(p,56,150,130)
#57 scRNA overview
nm<-'scrna_overview';p57a<-p1+theme(legend.position='none');p57b<-p2;mk<-tibble(cluster=paste0('C',1:10),marker=sample(paste0('Gene',1:40),10),effect=runif(10,.5,2));p57c<-ggplot(mk,aes(effect,reorder(marker,effect),color=cluster))+geom_point(size=3)+scale_color_manual(values=rep(pal,length.out=10))+labs(x='Marker effect',y=NULL)+th+theme(legend.position='none');p57d<-ggplot(as.data.frame(as.table(mat)),aes(Var2,Var1,fill=Freq))+geom_tile()+scale_fill_gradient2(low='#37659B',mid='white',high='#D65F5F')+theme_void()+theme(legend.position='right');sv((p57a|p57b)/(p57c|p57d),57,210,170)
#58 nebula map
nm<-'nebula_map';d58<-cells|>mutate(state=sample(c('Core','Halo','Other'),n(),T));p<-ggplot(d58,aes(x,y))+stat_density_2d(aes(fill=after_stat(level)),geom='polygon',bins=8,alpha=.75,color=NA)+scale_fill_viridis_c(option='magma')+geom_point(aes(color=state),size=.25,alpha=.45)+scale_color_manual(values=pal[1:3])+coord_equal()+theme_void()+theme(legend.position='right');sv(p,58,170,130)
#59 spider time curves
nm<-'spider_curves';d59<-expand_grid(day=0:10,id=1:30,group=c('A','B'))|>mutate(value=100*exp(-day/runif(n(),6,12))+rnorm(n(),0,4));p<-ggplot(d59,aes(day,value,group=id,color=group))+geom_line(alpha=.3,linewidth=.35)+stat_summary(aes(group=group),fun=mean,geom='line',linewidth=1.1)+facet_wrap(~group)+scale_color_manual(values=pal[1:2])+labs(x='Time after treatment',y='Tumour burden (%)')+th+theme(legend.position='none');sv(p,59,175,105)
#60 stacked longitudinal composition
nm<-'stacked_longitudinal';d60<-expand_grid(day=1:80,patient=paste0('P',1:4),clone=paste0('Clone',1:8))|>mutate(v=rgamma(n(),2));d60<-d60|>group_by(day,patient)|>mutate(frac=v/sum(v))|>ungroup();write.csv(d60,file.path(dd,'figure_060.csv'),row.names=F);p<-ggplot(d60,aes(day,frac,fill=clone))+geom_area(position='stack')+facet_wrap(~patient,ncol=1)+scale_fill_manual(values=pal)+labs(x='Time',y='Clonal fraction')+th+theme(legend.position='right');sv(p,60,185,170)
#61 multivariable matrix
nm<-'pair_matrix';d61<-data.frame(A=rnorm(180),B=rnorm(180),C=rnorm(180),D=rnorm(180),E=rnorm(180),group=sample(c('Ctrl','Treat'),180,T));write.csv(d61,file.path(dd,'figure_061.csv'),row.names=F);p<-GGally::ggpairs(d61,columns=1:5,mapping=aes(color=group,alpha=.45),upper=list(continuous=GGally::wrap('cor',size=3)),diag=list(continuous='densityDiag'))+theme_bw(base_family='Arial',base_size=7);sv(p,61,180,180)
#62 broken stacked bars
nm<-'broken_axis_bars';d62<-expand_grid(group=LETTERS[1:5],part=paste0('Type',1:6))|>mutate(value=sample(c(10:90,800:1400),n(),T));p<-ggplot(d62,aes(group,value,fill=part))+geom_col(position='stack',width=.65)+scale_fill_manual(values=pal[1:6])+ggbreak::scale_y_break(c(220,650),scales=.35)+labs(x=NULL,y='Cell count')+th+theme(legend.position='right');sv(p,62,155,140)
#63 3D scatter via plot3D
nm<-'three_dimensional_scatter';d63<-tibble(x=rnorm(240),y=rnorm(240),z=rnorm(240),group=sample(1:3,240,T));write.csv(d63,file.path(dd,'figure_063.csv'),row.names=F);ragg::agg_png(file.path(fd,'figure_063_three_dimensional_scatter.png'),1800,1600,res=300,bg='white');scatterplot3d::scatterplot3d(d63$x,d63$y,d63$z,color=pal[d63$group],pch=19,cex.symbols=.75,grid=TRUE,box=FALSE,angle=48,xlab='PC1',ylab='PC2',zlab='PC3');legend('topright',legend=paste('Group',1:3),col=pal[1:3],pch=19,bty='n');dev.off()
#64 circular volcano
nm<-'circular_volcano';d64<-expand_grid(cluster=paste0('C',1:12),gene=1:80)|>mutate(fc=rnorm(n(),0,1),idx=row_number(),sig=abs(fc)>1);p<-ggplot(d64,aes(idx,abs(fc),fill=cluster))+geom_col(width=.92)+geom_point(data=filter(d64,sig),aes(y=abs(fc)+.12),shape=21,size=.8,color='white')+coord_polar()+scale_fill_manual(values=rep(pal,length.out=12))+theme_void()+theme(legend.position='right');sv(p,64,155,150)
#65 geographic bubble network
nm<-'bubble_network_map';nodes<-tibble(name=paste0('N',1:55),x=runif(55),y=runif(55),size=runif(55,2,15),group=sample(1:5,55,T));ed<-tibble(a=sample(nodes$name,90,T),b=sample(nodes$name,90,T));g65<-igraph::graph_from_data_frame(ed,vertices=nodes,directed=F);p<-ggraph::ggraph(g65,layout='manual',x=nodes$x,y=nodes$y)+ggraph::geom_edge_link(color='#754668',alpha=.28,linewidth=.4)+ggraph::geom_node_point(aes(size=size,color=factor(group)),alpha=.8)+scale_color_manual(values=pal[1:5])+theme_void()+theme(legend.position='right');sv(p,65,180,115)
#66 issue 59 has historical rendered evidence; reused outside this script.
#67 weighted Voronoi-like treemap
nm<-'voronoi_treemap';d67<-tibble(group=rep(c('BRA','IND','CAN','CHN','USA','AUS'),each=8),value=runif(48,1,20),label=paste0('S',1:48));write.csv(d67,file.path(dd,'figure_067.csv'),row.names=F);p<-ggplot(d67,aes(area=value,fill=group,label=ifelse(value>12,label,'')))+treemapify::geom_treemap(color='white',linewidth=.5)+treemapify::geom_treemap_text(place='centre',grow=F,reflow=T,size=8)+scale_fill_manual(values=pal[1:6])+theme_void()+theme(legend.position='right');sv(p,67,180,125)
#68 decision curves
nm<-'decision_curve';d68<-tibble(threshold=seq(.01,.85,length.out=100));for(k in 1:6)d68[[paste0('Model ',k)]]<-(.22-.17*d68$threshold)*exp(-runif(1,.5,2)*d68$threshold)+rnorm(100,0,.003);long<-pivot_longer(d68,-threshold,names_to='model',values_to='benefit');write.csv(long,file.path(dd,'figure_068.csv'),row.names=F);p<-ggplot(long,aes(threshold,benefit,color=model))+geom_line(linewidth=.8)+geom_hline(yintercept=0,color='grey55',linetype=2)+scale_color_manual(values=pal[1:6])+labs(x='Threshold probability',y='Net benefit',color=NULL)+th+theme(legend.position='right');sv(p,68,170,115)
#69 annotated phylogenetic tree
nm<-'annotated_phylogeny';tr<-ape::rtree(55);meta<-tibble(label=tr$tip.label,group=sample(LETTERS[1:5],55,T),value=runif(55));p<-ggtree::ggtree(tr,layout='fan',size=.25)%<+%meta+ggtree::geom_tippoint(aes(color=group,size=value))+scale_color_manual(values=pal[1:5])+theme(legend.position='right');sv(p,69,175,165)
#70 enrichment network
nm<-'enrichment_network';terms<-paste('Pathway',1:32);g70<-igraph::sample_gnp(32,.1,directed=F);igraph::V(g70)$name<-terms;igraph::V(g70)$group<-sample(1:5,32,T);igraph::V(g70)$score<-runif(32,2,12);p<-ggraph::ggraph(g70,layout='fr')+ggraph::geom_edge_link(aes(width=after_stat(index)),color='grey70',alpha=.45)+ggraph::geom_node_point(aes(size=score,color=factor(group)))+ggraph::geom_node_text(aes(label=name),repel=T,size=2.4)+scale_color_manual(values=pal[1:5])+theme_void()+theme(legend.position='right');sv(p,70,180,135)
for(fp in list.files(fd,'^figure_(05[1-9]|06[0-9]|070)_.*png$',full.names=T)){im<-magick::image_read(fp)|>magick::image_trim()|>magick::image_border('white','24x24');magick::image_write(im,fp)}
writeLines(capture.output(sessionInfo()),file.path(root,'results/tables/sessionInfo_051_070.txt'))
