#!/usr/bin/env Rscript
suppressPackageStartupMessages({library(tidyverse);library(patchwork);library(ragg);library(ggrepel);library(ComplexHeatmap);library(circlize);library(ggridges);library(gghalves);library(ggsankey);library(ggsurvfit);library(survival);library(ggforce);library(ggside);library(linkET);library(vegan);library(ggnewscale);library(grid)})
dir.create('results/figures',recursive=T,showWarnings=F);dir.create('results/plot_data',recursive=T,showWarnings=F)
th=theme_classic(base_family='Arial',base_size=9); savep=function(n,p,w=150,h=110){agg_png(paste0('results/figures/',n,'.png'),w,h,units='mm',res=300,background='white');print(p);dev.off()}
# 21 bubble heatmap: size=P, fill=effect, tumor strip and row-group strip
set.seed(3021);d=expand_grid(pathway=factor(paste0('Pathway ',sprintf('%02d',1:28)),levels=rev(paste0('Pathway ',sprintf('%02d',1:28)))),patient=paste0('P',1:18))%>%mutate(effect=rnorm(n()),padj=runif(n())^3,tumor=c(HCC='HCC',CRC='CRC',NSCLC='NSCLC')[rep(c('HCC','CRC','NSCLC'),each=6)[match(patient,paste0('P',1:18))]],family=rep(c('Immune','Metabolic','Stress','DNA'),each=7)[match(as.character(pathway),paste0('Pathway ',sprintf('%02d',1:28)))]);p=ggplot(d,aes(patient,pathway))+geom_point(aes(size=-log10(padj),fill=effect),shape=21,color='grey25',stroke=.25)+scale_size(range=c(.15,4),name='-log10 adj. P')+scale_fill_gradient2(low='#2B6CB0',mid='white',high='#D73027',name='Effect')+facet_grid(family~tumor,scales='free',space='free')+labs(x=NULL,y=NULL)+th+theme(axis.text.x=element_text(angle=90,hjust=1,size=6),axis.text.y=element_text(size=6),strip.background=element_rect(fill='grey94'),legend.position='right');savep('21_bubble_heatmap',p,180,160);write.csv(d,'results/plot_data/21_bubble_heatmap.csv',row.names=F)
# 22 real linkET Mantel network + upper correlation matrix
data(varespec, package="vegan"); data(varechem, package="vegan")
set.seed(3022)
mantel22=mantel_test(varespec,varechem,spec_select=list(`Taxonomic composition`=1:12,`Gene functional composition`=13:24))%>%mutate(rd=cut(r,breaks=c(-Inf,.2,.4,Inf),labels=c("<0.2","0.2-0.4",">=0.4")),pd=cut(p,breaks=c(-Inf,.01,.05,Inf),labels=c("<0.01","0.01-0.05",">=0.05")))
p=qcorrplot(correlate(varechem),type="upper",diag=FALSE,grid_col=NA)+geom_square()+geom_mark(size=2.6,sig_thres=.05,sep="")+geom_couple(data=mantel22,aes(color=pd,size=rd),curvature=nice_curvature(by="from"),nudge_x=.18)+scale_fill_gradientn(limits=c(-.8,.8),colors=rev(RColorBrewer::brewer.pal(11,"Spectral")))+scale_size_manual(values=c(.45,1.1,2.1))+scale_color_manual(values=c("<0.01"="#D73027","0.01-0.05"="#FC8D59",">=0.05"="#91BFDB"))+guides(size=guide_legend(title="Mantel r",order=2),colour=guide_legend(title="Mantel P",order=1),fill=guide_colorbar(title="Pearson r",order=3))+theme(legend.box.spacing=unit(0,"pt"),text=element_text(family="Arial",size=9));savep("22_mantel_network_heatmap",p,175,130);write.csv(mantel22,"results/plot_data/22_mantel.csv",row.names=F)
# 23 combined triangular multi-track heatmap
set.seed(3023);n=34;m=matrix(rnorm(n*n),n);diag(m)=NA;mplot=m;mplot[lower.tri(mplot)]=NA;grp=rep(LETTERS[1:4],length.out=n);cf=colorRamp2(c(-2,0,2),c('#2166AC','white','#B2182B'));ha=HeatmapAnnotation(Group=grp,col=list(Group=setNames(c('#4E79A7','#F28E2B','#59A14F','#E15759'),LETTERS[1:4])));ht=Heatmap(mplot,name='Z score',col=cf,na_col='white',cluster_rows=F,cluster_columns=F,show_row_names=F,show_column_names=F,top_annotation=ha,border=T,cell_fun=function(j,i,x,y,w,h,fill){if(i>j)grid.circle(x,y,r=unit(abs(m[i,j])/max(abs(m),na.rm=T)*1.6,'mm'),gp=gpar(fill=ifelse(m[i,j]>0,'#D6604D','#4393C3'),col=NA))});agg_png('results/figures/23_combined_heatmap.png',150,135,units='mm',res=300,background='white');draw(ht,heatmap_legend_side='bottom');dev.off();write.csv(m,'results/plot_data/23_matrix.csv',row.names=F)
# 24 ridgeline + clinical dot and mutation burden tracks
set.seed(3024);patients=paste0('P',1:14);rd=expand_grid(patient=factor(patients,levels=rev(patients)),cell=1:160)%>%mutate(score=rnorm(n(),rep(seq(-.5,.6,length.out=14),each=160),.55),smoking=rep(sample(c('Never','Former','Current'),14,T),each=160));summ=rd%>%group_by(patient)%>%summarise(smoking=first(smoking),TMB=rgamma(1,3,1),.groups='drop');ridge=ggplot(rd,aes(score,patient,fill=patient))+geom_density_ridges(scale=1.1,alpha=.8,color='white',linewidth=.25)+theme_ridges(font_family='Arial',font_size=8,grid=F)+theme(legend.position='none')+labs(x='CytoTRACE score',y=NULL);dot=ggplot(summ,aes(1,patient,fill=smoking))+geom_point(shape=21,size=3)+scale_fill_manual(values=c(Never='#59A14F',Former='#F28E2B',Current='#8C8C8C'))+theme_void()+theme(legend.position='bottom');bar=ggplot(summ,aes(TMB,patient))+geom_col(fill='#A77D51',width=.42)+th+theme(axis.text.y=element_blank(),axis.title.y=element_blank())+labs(x='Mutations per Mb');savep('24_ridge_tracks',ridge+dot+bar+plot_layout(widths=c(4,1.2,1.6),guides='collect'),180,125);write.csv(rd,'results/plot_data/24_ridge.csv',row.names=F)
# 25 violin, raincloud, paired progression panels
set.seed(3025);v=expand_grid(celltype=factor(c('KAC','AICs','AT2','AT1')),rep=1:42)%>%mutate(score=rnorm(n(),c(.35,.55,.7,.82)[celltype],.11));a=ggplot(v,aes(celltype,score,fill=celltype))+geom_violin(trim=F,width=.8)+geom_boxplot(width=.13,fill='white',outlier.shape=NA)+labs(x=NULL,y='Cell score')+th+theme(legend.position='none');b=ggplot(v,aes(celltype,score,fill=celltype))+geom_half_violin(side='l',trim=F)+geom_boxplot(width=.12,outlier.shape=NA)+geom_jitter(width=.08,size=.55,alpha=.45)+labs(x=NULL,y='Cell score')+th+theme(legend.position='none');paired=expand_grid(id=1:18,stage=factor(c('NL','AAH','LUAD'),levels=c('NL','AAH','LUAD')))%>%mutate(score=.3+as.numeric(stage)*.18+rnorm(n(),0,.09));c=ggplot(paired,aes(stage,score,group=id))+geom_line(color='grey70')+geom_point(aes(fill=stage),shape=21,size=2)+geom_boxplot(aes(group=stage),width=.35,fill=NA,outlier.shape=NA)+labs(x=NULL,y='KAC signature')+th+theme(legend.position='none');savep('25_violin_raincloud_paired',a+b+c,180,90);write.csv(v,'results/plot_data/25_violin.csv',row.names=F);write.csv(paired,'results/plot_data/25_paired.csv',row.names=F)
# 26 FC-FC scatter with quadrant colors and sparse labels
set.seed(3026);d=tibble(gene=paste0('G',1:4200),mRNA=sort(runif(4200,0,5000)),FDR=runif(4200));d$protein=1.7*tanh((d$mRNA-2500)/1050)+rnorm(4200,0,.42);d$state=case_when(d$protein > 0.55 & d$FDR < 0.15~'ERK-dependent UP',d$protein < -0.55 & d$FDR < 0.15~'ERK-dependent DN',TRUE~'N.S.');lab=d%>%filter(state!='N.S.')%>%slice_max(abs(protein),n=8);p=ggplot(d,aes(mRNA,protein))+geom_point(aes(color=state),size=.7,alpha=.45)+geom_hline(yintercept=0)+geom_smooth(method='loess',se=F,color='black',linewidth=.45)+geom_text_repel(data=lab,aes(label=gene),size=2.5,seed=5)+scale_color_manual(values=c('ERK-dependent UP'='#E64B35','ERK-dependent DN'='#00A087','N.S.'='grey78'))+labs(x='mRNA (rank of FC)',y='Protein (logFC)',color=NULL)+th+theme(legend.position=c(.18,.88));savep('26_fc_fc_scatter',p,135,105);write.csv(d,'results/plot_data/26_fc_fc.csv',row.names=F)
# 27 multi-stage alluvial Sankey
set.seed(3027);raw=tibble(id=1:170,Region=sample(c('Africa','Asia','Europe','Americas'),170,T),Class=sample(c('Mammal','Bird','Reptile'),170,T),Status=sample(c('Stable','Declining','Unknown'),170,T),Outcome=sample(c('Protected','Unprotected'),170,T));sk=make_long(raw,Region,Class,Status,Outcome);p=ggplot(sk,aes(x=x,next_x=next_x,node=node,next_node=next_node,fill=factor(node),label=node))+geom_sankey(flow.alpha=.55,node.color='grey20',show.legend=F)+geom_sankey_text(size=2.7,color='black')+scale_fill_viridis_d(option='D')+theme_sankey(base_size=9,base_family='Arial')+labs(x=NULL);savep('27_sankey',p,180,100);write.csv(raw,'results/plot_data/27_sankey.csv',row.names=F)
# 28 ggsurvfit curve + aligned risk table
set.seed(3028);sd=tibble(time=rexp(240,rate=rep(c(.055,.035),each=120)),status=rbinom(240,1,.78),group=rep(c('Standard care','Combination therapy'),each=120));fit=survfit2(Surv(time,status)~group,data=sd);p=ggsurvfit(fit,type='survival')+add_confidence_interval(alpha=.12)+add_censor_mark(size=1.4)+add_risktable(risktable_stats=c('{n.risk} ({cum.event})'),stats_label='No. at risk (events)')+scale_color_manual(values=c('#2C7FB8','#D95F59'))+labs(x='Time since randomization (months)',y='Overall survival probability',color=NULL)+theme_classic(base_family='Arial',base_size=9)+theme(legend.position='top');savep('28_survival_risktable',p,165,125);write.csv(sd,'results/plot_data/28_survival.csv',row.names=F)
# 29 lollipop with aligned type strip + three separated donuts
set.seed(3029);ld=tibble(cell=factor(paste0('Cell ',1:13),levels=paste0('Cell ',1:13)),count=sample(120:920,13),type=rep(c('Immune','Stromal','Epithelial'),length.out=13));l=ggplot(ld,aes(cell,count,color=type))+geom_segment(aes(xend=cell,y=0,yend=count),linewidth=.65)+geom_point(size=3)+geom_text(aes(label=count),vjust=-.7,size=2.4)+scale_color_brewer(palette='Dark2')+labs(x=NULL,y='No. of cells')+th+theme(axis.text.x=element_text(angle=45,hjust=1),legend.position='none');don=expand_grid(sample=c('S1','S2','S3'),type=c('CD4 T','CD8 T','B','NK'))%>%mutate(v=runif(n(),1,9));q=ggplot(don,aes(x=2,y=v,fill=type))+geom_col(width=.9,color='white')+coord_polar(theta='y')+xlim(.55,2.5)+facet_wrap(~sample)+scale_fill_brewer(palette='Set2')+theme_void(base_family='Arial')+theme(legend.position='bottom');savep('29_lollipop_donuts',l/q+plot_layout(heights=c(1.15,1)),175,150);write.csv(ld,'results/plot_data/29_lollipop.csv',row.names=F);write.csv(don,'results/plot_data/29_donuts.csv',row.names=F)
# 30 scatter with ggside marginal density/boxplot
set.seed(3030);d=bind_rows(lapply(1:5,function(i)tibble(group=paste('Experiment',i),PC1=rnorm(230,(i-3)*.08,.22),PC2=rnorm(230,(3-i)*.06,.2))));p=ggplot(d,aes(PC1,PC2,color=group,fill=group))+geom_point(size=.75,alpha=.5)+geom_xsidedensity(alpha=.45,linewidth=.3)+geom_ysidedensity(alpha=.45,linewidth=.3)+scale_color_brewer(palette='Set1')+scale_fill_brewer(palette='Set1')+labs(x='Principal component 1',y='Principal component 2',color=NULL,fill=NULL)+theme_classic(base_family='Arial',base_size=9)+theme(legend.position=c(.2,.15),ggside.panel.scale=.22);savep('30_scatter_marginals',p,140,120);write.csv(d,'results/plot_data/30_scatter.csv',row.names=F)
cat('BATCH_21_30_OK\n')

# ----- fidelity correction after strict source-code audit -----
# 22: preserve linkET's circle matrix and Mantel coupling geometry
p22=qcorrplot(correlate(varechem),type='upper',diag=FALSE,grid_col=NA)+geom_point(shape=21,size=7,fill=NA,stroke=.3,color='black')+geom_point(aes(size=abs(r),fill=r),shape=21,stroke=.3,color='black')+scale_size(range=c(1,7),guide='none')+ggnewscale::new_scale('size')+geom_couple(data=mantel22,aes(color=pd,size=rd),curvature=nice_curvature(by='from'),nudge_x=.18)+scale_fill_gradientn(limits=c(-.8,.8),colors=rev(RColorBrewer::brewer.pal(11,'Spectral')))+scale_size_manual(values=c(.5,1.4,2.5))+scale_color_manual(values=c('<0.01'='#D73027','0.01-0.05'='#FC8D59','>=0.05'='#91BFDB'))+guides(size=guide_legend(title='Mantel r',order=2),colour=guide_legend(title='Mantel P',order=1),fill=guide_colorbar(title='Pearson r',order=3))+theme(text=element_text(family='Arial',size=9),legend.box.spacing=unit(0,'pt'));savep('22_mantel_network_heatmap',p22,175,130)
# 23: one aligned matrix with true upper/lower triangular glyphs
set.seed(4023);n=42;adj=matrix(runif(n*n),n);corr=matrix(runif(n*n,-1,1),n);blank=matrix(NA_real_,n,n);gp=rep(LETTERS[1:4],length.out=n); ha=HeatmapAnnotation(Group=gp,col=list(Group=setNames(c('#4E79A7','#F28E2B','#59A14F','#E15759'),LETTERS[1:4])));red=colorRamp2(c(0,.5,1),c('white','#F4A582','#B2182B'));green=colorRamp2(c(-1,0,1),c('#762A83','white','#1B7837'));tri=Heatmap(blank,name='Combined',na_col='white',cluster_rows=F,cluster_columns=F,show_row_names=F,show_column_names=F,top_annotation=ha,border=T,show_heatmap_legend=F,cell_fun=function(j,i,x,y,w,h,fill){if(i<j)grid.polygon(x=unit.c(x-w/2,x+w/2,x+w/2),y=unit.c(y+h/2,y+h/2,y-h/2),gp=gpar(fill=red(adj[i,j]),col=NA));if(i>j)grid.polygon(x=unit.c(x-w/2,x-w/2,x+w/2),y=unit.c(y+h/2,y-h/2,y-h/2),gp=gpar(fill=green(corr[i,j]),col=NA));if(i==j)grid.rect(x,y,w,h,gp=gpar(fill='grey92',col=NA))});agg_png('results/figures/23_combined_heatmap.png',155,145,units='mm',res=300,background='white');draw(tri,padding=unit(c(8,8,8,8),'mm'));draw(Legend(col_fun=red,title='Adjacency'),x=unit(.44,'npc'),y=unit(.08,'npc'),just=c('right','bottom'));draw(Legend(col_fun=green,title='Correlation'),x=unit(.56,'npc'),y=unit(.08,'npc'),just=c('left','bottom'));dev.off();write.csv(adj,'results/plot_data/23_adjacency.csv',row.names=F);write.csv(corr,'results/plot_data/23_correlation.csv',row.names=F)
# 26: source-coded rank axis, low-opacity category layers, marked APC/C genes
set.seed(4026);n=4300;rankv=sort(sample(1:12000,n));fc=1.65*tanh((rankv-6000)/2600)+rnorm(n,0,.36);fdr=runif(n);dd=tibble(gene=paste0('G',1:n),rank=rankv,protein=fc,FDR=fdr)%>%mutate(group=case_when(protein > 0.5 & FDR < 0.18~'ERK-dependent (UP)',protein < -0.5 & FDR < 0.18~'ERK-suppressed (DN)',TRUE~'N.S.'));ids=c(which.min(dd$protein),which.max(dd$protein),order(abs(dd$protein),decreasing=T)[3:6]);dd$gene[ids]=c('CCNB1','CCNB2','PTTG1','CDC20','BUB1','UBE2C');p26=ggplot(dd,aes(rank,protein))+geom_point(aes(color=group,fill=group),shape=21,size=1,stroke=.45,alpha=.14)+geom_point(data=dd[ids,],shape=21,size=1.9,stroke=.8,color='black',aes(fill=group))+geom_text_repel(data=dd[ids,],aes(label=gene),size=2.7,color='black',seed=2,min.segment.length=0)+geom_hline(yintercept=0,linetype=3)+annotate('point',x=10500,y=-2.2,shape=21,size=2.2,fill='grey60')+annotate('text',x=10800,y=-2.2,label='APC/C\nsubstrates',hjust=0,size=2.8)+scale_x_continuous(breaks=c(0,3000,6000,9000,12000),labels=c(0,1000,2000,3000,4000))+scale_color_manual(values=c('ERK-dependent (UP)'='#F80000','ERK-suppressed (DN)'='#0080BB','N.S.'='#00B137'))+scale_fill_manual(values=c('ERK-dependent (UP)'='#F80000','ERK-suppressed (DN)'='#0080BB','N.S.'='#00B137'))+labs(x='mRNA (rank of FC)',y='Protein (log2FC)',title='ERKi (24h)',color='mRNA',fill='mRNA')+th+theme(plot.title=element_text(hjust=.5),legend.position=c(.22,.84));savep('26_fc_fc_scatter',p26,145,100);write.csv(dd,'results/plot_data/26_fc_fc.csv',row.names=F)
# 28: restore previously validated ggsurvfit visual contract with risk table, censor marks, median line
lung=survival::lung%>%filter(complete.cases(time,status,sex))%>%mutate(group=factor(sex,levels=c(1,2),labels=c('Placebo + CF','Serplulimab + CF')));fit28=survfit2(Surv(time/30.4375,status==2)~group,data=lung);p28=fit28|>ggsurvfit(linewidth=.8)+add_risktable(risktable_height=.28,risktable_stats='{n.risk} ({cum.censor})',stats_label=list(n.risk='Number at risk',cum.censor='number censored'),size=3.2,hjust=.5)+add_risktable_strata_symbol(symbol='●',size=9)+add_censor_mark(size=2,shape=3)+add_quantile(y_value=.5,linetype='dashed',color='#4B4B4B',linewidth=.45)+labs(x='Time since randomization (months)',y='Overall survival (%)')+scale_x_continuous(breaks=seq(0,32,4),limits=c(-2.2,34.2),expand=c(0,0))+scale_y_continuous(breaks=seq(0,1,.25),labels=seq(0,100,25),limits=c(0,1),expand=c(0,0))+scale_color_manual(values=c('#E05133','#4877B9'))+scale_fill_manual(values=c('#E05133','#4877B9'))+theme_classic(base_family='Arial',base_size=10)+theme(legend.title=element_blank(),legend.position=c(.18,.16),plot.margin=margin(5,8,2,6));savep('28_survival_risktable',p28,180,125);write.csv(lung,'results/plot_data/28_survival.csv',row.names=F)
cat('FIDELITY_CORRECTION_OK\n')
# 25 layout correction: portrait stack matching source information hierarchy
p25a=ggplot(v,aes(celltype,score,fill=celltype))+geom_violin(trim=F,width=.72,color='grey30')+geom_boxplot(width=.11,fill='white',outlier.shape=NA)+stat_summary(fun=mean,geom='point',shape=21,size=1.8,fill='black')+labs(x=NULL,y='Alveolar score')+th+theme(legend.position='none')
p25b=ggplot(v,aes(celltype,score,fill=celltype))+geom_half_violin(side='l',trim=F,width=.8,color=NA)+geom_boxplot(width=.12,outlier.shape=NA)+geom_jitter(width=.07,size=.55,alpha=.38,color='grey35')+coord_flip()+labs(x=NULL,y='Cell score')+th+theme(legend.position='none')
p25c=ggplot(paired,aes(stage,score,group=id))+geom_line(color='grey65',linewidth=.35)+geom_point(aes(fill=stage),shape=21,size=2)+geom_boxplot(aes(group=stage),width=.28,fill=NA,outlier.shape=NA)+labs(x=NULL,y='KAC signature')+th+theme(legend.position='none')
savep('25_violin_raincloud_paired',p25a/p25b/p25c+plot_layout(heights=c(1,1.35,1)),105,180)
# 27 density correction: more nodes and flows while retaining ggsankey core geometry
set.seed(4027);raw27=tibble(id=1:420,Input=sample(paste0('Input ',1:5),420,T),Region=sample(c('Africa','Asia','Europe','Americas','Oceania'),420,T),Taxon=sample(c('Mammal','Bird','Reptile','Amphibian','Fish','Plant'),420,T),Threat=sample(c('Habitat loss','Climate','Harvest','Disease','Pollution','None'),420,T),Outcome=sample(c('Protected','Managed','Unresolved','Declining'),420,T));sk27=make_long(raw27,Input,Region,Taxon,Threat,Outcome);p27=ggplot(sk27,aes(x=x,next_x=next_x,node=node,next_node=next_node,fill=factor(node),label=node))+geom_sankey(flow.alpha=.42,node.color='grey25',node.size=2.4,width=.12,show.legend=F)+geom_sankey_text(size=2.15,color='black')+scale_fill_viridis_d(option='D')+theme_sankey(base_size=8,base_family='Arial')+labs(x=NULL)+theme(plot.margin=margin(6,12,6,12));savep('27_sankey',p27,190,105);write.csv(raw27,'results/plot_data/27_sankey.csv',row.names=F)
cat('LAYOUT_DENSITY_CORRECTION_OK\n')

# ----- overlap/stroke correction after object-level visual inspection -----
# 22: reserve a dedicated left label gutter and right legend gutter
p22f=p22+coord_cartesian(clip='off')+theme(plot.margin=margin(8,34,8,72),legend.position='right',legend.box='vertical')
savep('22_mantel_network_heatmap',p22f,190,135)
# 23: reserve 30 mm below matrix; legends sit in that dedicated slot
agg_png('results/figures/23_combined_heatmap.png',165,155,units='mm',res=300,background='white');draw(tri,padding=unit(c(8,8,32,8),'mm'));lg1=Legend(col_fun=red,title='Adjacency',direction='horizontal',legend_width=unit(38,'mm'));lg2=Legend(col_fun=green,title='Correlation',direction='horizontal',legend_width=unit(38,'mm'));draw(packLegend(lg1,lg2,direction='horizontal',gap=unit(12,'mm')),x=unit(.5,'npc'),y=unit(.055,'npc'),just=c('center','bottom'));dev.off()
# 27: remove node outlines; keep thin label hierarchy and add horizontal breathing room
p27f=ggplot(sk27,aes(x=x,next_x=next_x,node=node,next_node=next_node,fill=factor(node),label=node))+geom_sankey(flow.alpha=.38,node.color=NA,node.size=1.1,width=.11,show.legend=F)+geom_sankey_text(size=2.05,color='#202020')+scale_fill_viridis_d(option='D')+theme_sankey(base_size=8,base_family='Arial')+labs(x=NULL)+theme(plot.margin=margin(8,22,8,22));savep('27_sankey',p27f,195,108)
# 29: reduce and rotate dense category labels; preserve separate donut row
l29=ggplot(ld,aes(cell,count,color=type))+geom_segment(aes(xend=cell,y=0,yend=count),linewidth=.42)+geom_point(size=2.6)+geom_text(aes(label=count),vjust=-.72,size=2.1)+scale_color_brewer(palette='Dark2')+labs(x=NULL,y='No. of cells')+th+theme(axis.text.x=element_text(angle=58,hjust=1,vjust=1,size=6.4),legend.position='none',plot.margin=margin(5,8,12,8));savep('29_lollipop_donuts',l29/q+plot_layout(heights=c(1.05,1)),175,155)
# 30: move legend into its own bottom slot; keep side panels free of labels
p30=ggplot(d,aes(PC1,PC2,color=group,fill=group))+geom_point(size=.75,alpha=.5)+geom_xsidedensity(alpha=.38,linewidth=.3)+geom_ysidedensity(alpha=.38,linewidth=.3)+scale_color_brewer(palette='Set1')+scale_fill_brewer(palette='Set1')+labs(x='Principal component 1',y='Principal component 2',color=NULL,fill=NULL)+theme_classic(base_family='Arial',base_size=9)+theme(legend.position='bottom',legend.direction='horizontal',legend.box='horizontal',ggside.panel.scale=.20,plot.margin=margin(6,8,4,6))+guides(color=guide_legend(nrow=1,override.aes=list(size=2,alpha=1)),fill='none');savep('30_scatter_marginals',p30,150,130)
cat('OVERLAP_STROKE_CORRECTION_OK\n')
# 23 final correction: independent heatmap and legend viewports
agg_png('results/figures/23_combined_heatmap.png',170,165,units='mm',res=300,background='white');grid.newpage();pushViewport(viewport(x=.5,y=.59,width=.92,height=.76));draw(tri,newpage=FALSE,padding=unit(c(3,3,3,3),'mm'));popViewport();lg1=Legend(col_fun=red,title='Adjacency',direction='horizontal',legend_width=unit(42,'mm'));lg2=Legend(col_fun=green,title='Correlation',direction='horizontal',legend_width=unit(42,'mm'));draw(packLegend(lg1,lg2,direction='horizontal',gap=unit(15,'mm')),x=unit(.5,'npc'),y=unit(.045,'npc'),just=c('center','bottom'));dev.off();cat('HEATMAP_VIEWPORT_GATE_OK\n')
